project:
  type: website
  render: 
    # Render all .qmd files
    - "**/*.qmd"
     # Except in presentations/
    - "!presentations/"
    - "!bleaching_analysis/"
    # Don't include the tasks, they need to be rendered separately for one version with and without solutions
    - "!tasks_part1.qmd"
    - "!tasks_part2.qmd"
  # but use the output (needs to be rendered before)  
  resources:
    - "presentations/output"
    - "bleaching_analysis.zip"
    # needs to be moved manually
    - "tasks_output/"
    
website:
  title: TP Environmental Risk
  search: false
  navbar:
    search: false
    collapse: false
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/andieich/practicals_envrisk
          - text: Report a Bug
            href: https://github.com/andieich/practicals_envrisk/issues/new
 



  page-footer:
    left: |
     Andreas Eich
    right: |
      © 2025
format: html
highlight-style: monokai
